/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.CardLayout;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;

/**
 *
 * @author ASUS
 */
public class PenampilGambarButton extends javax.swing.JFrame {

    /**
     * Creates new form PenampilGambarButton
     */
    public PenampilGambarButton() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnPanel = new javax.swing.JPanel();
        BtnMouse = new javax.swing.JButton();
        BtnKeyboard = new javax.swing.JButton();
        BtnMonitor = new javax.swing.JButton();
        BtnKeluar = new javax.swing.JButton();
        IMGPanel = new javax.swing.JPanel();
        lblMouse = new javax.swing.JLabel();
        lblKeyboard = new javax.swing.JLabel();
        lblMonitor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        BtnMouse.setText("Mouse");
        BtnMouse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnMouse.setPreferredSize(new java.awt.Dimension(130, 30));
        BtnMouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMouseActionPerformed(evt);
            }
        });
        BtnPanel.add(BtnMouse);

        BtnKeyboard.setText("Keyboard");
        BtnKeyboard.setPreferredSize(new java.awt.Dimension(130, 30));
        BtnKeyboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeyboardActionPerformed(evt);
            }
        });
        BtnPanel.add(BtnKeyboard);

        BtnMonitor.setText("Monitor");
        BtnMonitor.setPreferredSize(new java.awt.Dimension(130, 30));
        BtnMonitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMonitorActionPerformed(evt);
            }
        });
        BtnPanel.add(BtnMonitor);

        BtnKeluar.setText("Keluar");
        BtnKeluar.setPreferredSize(new java.awt.Dimension(130, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnPanel.add(BtnKeluar);

        getContentPane().add(BtnPanel, java.awt.BorderLayout.CENTER);

        IMGPanel.setLayout(new java.awt.CardLayout());

        lblMouse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMouse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Mouse.jpg"))); // NOI18N
        lblMouse.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblMouse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        IMGPanel.add(lblMouse, "0");

        lblKeyboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKeyboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/keyboard.jpg"))); // NOI18N
        lblKeyboard.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        IMGPanel.add(lblKeyboard, "1");

        lblMonitor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMonitor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/monitor.jpg"))); // NOI18N
        IMGPanel.add(lblMonitor, "2");

        getContentPane().add(IMGPanel, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnMouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMouseActionPerformed
        CardLayout c1 = (CardLayout)(IMGPanel.getLayout());
        c1.show(IMGPanel, "0");
    }//GEN-LAST:event_BtnMouseActionPerformed

    private void BtnKeyboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeyboardActionPerformed
        CardLayout c1 = (CardLayout)(IMGPanel.getLayout());
        c1.show(IMGPanel, "1");
    }//GEN-LAST:event_BtnKeyboardActionPerformed

    private void BtnMonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMonitorActionPerformed
        CardLayout c1 = (CardLayout)(IMGPanel.getLayout());
        c1.show(IMGPanel, "2");
    }//GEN-LAST:event_BtnMonitorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenampilGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenampilGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenampilGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenampilGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                PenampilGambarButton fullFrame = new PenampilGambarButton();
                
                GraphicsDevice device =
                        GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
                device.setFullScreenWindow(fullFrame);
                
                fullFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnKeluar;
    private javax.swing.JButton BtnKeyboard;
    private javax.swing.JButton BtnMonitor;
    private javax.swing.JButton BtnMouse;
    private javax.swing.JPanel BtnPanel;
    private javax.swing.JPanel IMGPanel;
    private javax.swing.JLabel lblKeyboard;
    private javax.swing.JLabel lblMonitor;
    private javax.swing.JLabel lblMouse;
    // End of variables declaration//GEN-END:variables
}
